INSERT INTO tbl_times (nome_time) VALUES
('Real Madruga FC'),
('Velhice FC'),
('Ponte Branca'),
('Eclipse Azul'),
('Real Vilinha'),
('Só Canelas FC'),
('Martinico FC'),
('Bahia de Munique FC');


INSERT INTO tbl_jogadores (nome_jogador, time_jogador) VALUES
('Lucas', 1 ),
('Mariana', 1 ),
('Carlos', 1 ),
('Fernanda',1 ),
('João', 1),
('Ana', 2),
('Pedro', 2),
('Juliana', 2),
('Rafael', 2),
('Camila', 2),
('Bruno', 3),
('Patrícia', 3),
('Gabriel', 3),
('Larissa', 3),
('Felipe',3 ),
('Amanda', 4),
('Ricardo', 4),
('Bianca', 4),
('Thiago', 4),
('Beatriz', 4),
('Leonardo', 5),
('Natália', 5),
('Eduardo', 5),
('Isabela', 5),
('Vinícius', 5),
('Carolina', 6 ),
('André', 6 ),
('Letícia', 6 ),
('Gustavo', 6 ),
('Daniela', 6 ),
('Matheus', 7 ),
('Vanessa', 7 ),
('Diego',7 ),
('Renata',7 ),
('Henrique', 7 ),
('Aline',8 ),
('Marcelo', 8 ),
('Tatiane', 8 ),
('Rodrigo', 8 ),
('Sabrina', 8 );


INSERT INTO tbl_partidas_realizadas (placar_vencedor, placar_perdedor, time_vencedor, time_perdedor) VALUES
(3, 1, 1, 2),
(2, 0, 3, 4),
(1, 0, 5, 6),
(4, 2, 7, 8);